/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TubRouteImport } from './routes/tub'
import { Route as SwingRouteImport } from './routes/swing'
import { Route as SlidingRouteImport } from './routes/sliding'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as FixedRouteImport } from './routes/fixed'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as IndexRouteImport } from './routes/index'

const TubRoute = TubRouteImport.update({
  id: '/tub',
  path: '/tub',
  getParentRoute: () => rootRouteImport,
} as any)
const SwingRoute = SwingRouteImport.update({
  id: '/swing',
  path: '/swing',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidingRoute = SlidingRouteImport.update({
  id: '/sliding',
  path: '/sliding',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const FixedRoute = FixedRouteImport.update({
  id: '/fixed',
  path: '/fixed',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/custom': typeof CustomRoute
  '/fixed': typeof FixedRoute
  '/library': typeof LibraryRoute
  '/safety': typeof SafetyRoute
  '/sliding': typeof SlidingRoute
  '/swing': typeof SwingRoute
  '/tub': typeof TubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom': typeof CustomRoute
  '/fixed': typeof FixedRoute
  '/library': typeof LibraryRoute
  '/safety': typeof SafetyRoute
  '/sliding': typeof SlidingRoute
  '/swing': typeof SwingRoute
  '/tub': typeof TubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/custom': typeof CustomRoute
  '/fixed': typeof FixedRoute
  '/library': typeof LibraryRoute
  '/safety': typeof SafetyRoute
  '/sliding': typeof SlidingRoute
  '/swing': typeof SwingRoute
  '/tub': typeof TubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/custom'
    | '/fixed'
    | '/library'
    | '/safety'
    | '/sliding'
    | '/swing'
    | '/tub'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/custom'
    | '/fixed'
    | '/library'
    | '/safety'
    | '/sliding'
    | '/swing'
    | '/tub'
  id:
    | '__root__'
    | '/'
    | '/custom'
    | '/fixed'
    | '/library'
    | '/safety'
    | '/sliding'
    | '/swing'
    | '/tub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomRoute: typeof CustomRoute
  FixedRoute: typeof FixedRoute
  LibraryRoute: typeof LibraryRoute
  SafetyRoute: typeof SafetyRoute
  SlidingRoute: typeof SlidingRoute
  SwingRoute: typeof SwingRoute
  TubRoute: typeof TubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tub': {
      id: '/tub'
      path: '/tub'
      fullPath: '/tub'
      preLoaderRoute: typeof TubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swing': {
      id: '/swing'
      path: '/swing'
      fullPath: '/swing'
      preLoaderRoute: typeof SwingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sliding': {
      id: '/sliding'
      path: '/sliding'
      fullPath: '/sliding'
      preLoaderRoute: typeof SlidingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixed': {
      id: '/fixed'
      path: '/fixed'
      fullPath: '/fixed'
      preLoaderRoute: typeof FixedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomRoute: CustomRoute,
  FixedRoute: FixedRoute,
  LibraryRoute: LibraryRoute,
  SafetyRoute: SafetyRoute,
  SlidingRoute: SlidingRoute,
  SwingRoute: SwingRoute,
  TubRoute: TubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
